### ISSUE TITLE
Exceptions in Rainbow/Planner

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#90]
@javier-camara I get this exceptions when running `cp1`:
```
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
cp1_ta    | java.util.NoSuchElementException
cp1_ta    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
cp1_ta    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
cp1_ta    | 	at org.sa.rainbow.brass.plan.p2_cp1.DecisionEngineCP1.selectPolicy(DecisionEngineCP1.java:54)
cp1_ta    | 	at org.sa.rainbow.brass.adaptation.p2_cp1.CP1BRASSAdaptationPlanner.runAction(CP1BRASSAdaptationPlanner.java:212)
cp1_ta    | 	at org.sa.rainbow.core.AbstractRainbowRunnable.run(AbstractRainbowRunnable.java:246)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by javier-camara** [comment]
This was related to a change that I had to do to run things in my machine locally, and forgot to undo before pushing (related to the path of the configuration json file). I believe I have fixed the issue now. Can you try again after updating?

**Comment by pooyanjamshidi** [comment]
@javier-camara  Not fixed yet, see below, it tries to read from your dropbox ;)

```
cp1_ta    | LD_LIBRARY_PATH=/home/mars/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/mars/das/prism-4.3.1-linux64/lib
cp1_ta    | Will wait 130 seconds for Rainbow to come up
cp1_ta    | [INFO] [1526404736.509347]: Battery charge: 1.1639141293843343Ah
cp1_ta    | Starting /home/mars/das/rainbow-brass/run-oracle.sh brass-p2-cp1
cp1_ta    | java.io.FileNotFoundException: /Users/jcamara/Dropbox/Documents/Work/projects/rainbow-alt/deployments/rainbow-brass/prismtmp/p2cp1/config_list.json (No such file or directory)
cp1_ta    | 	at java.io.FileInputStream.open0(Native Method)
cp1_ta    | 	at java.io.FileInputStream.open(FileInputStream.java:195)
cp1_ta    | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
cp1_ta    | 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
cp1_ta    | 	at java.io.FileReader.<init>(FileReader.java:58)
cp1_ta    | 	at org.sa.rainbow.brass.confsynthesis.SimpleConfigurationStore.loadFromFile(SimpleConfigurationStore.java:51)
cp1_ta    | 	at org.sa.rainbow.brass.confsynthesis.SimpleConfigurationStore.populate(SimpleConfigurationStore.java:35)
cp1_ta    | 	at org.sa.rainbow.brass.analyses.p2_cp1.EnergyConsumptionAnalyzer.initialize(EnergyConsumptionAnalyzer.java:47)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.initializeRainbowComponents(RainbowMaster.java:209)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.initialize(RainbowMaster.java:131)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.main(RainbowMaster.java:798)
cp1_ta    | Exception in thread "main" java.lang.NullPointerException
cp1_ta    | 	at org.sa.rainbow.brass.confsynthesis.SimpleConfigurationStore.loadFromFile(SimpleConfigurationStore.java:59)
cp1_ta    | 	at org.sa.rainbow.brass.confsynthesis.SimpleConfigurationStore.populate(SimpleConfigurationStore.java:35)
cp1_ta    | 	at org.sa.rainbow.brass.analyses.p2_cp1.EnergyConsumptionAnalyzer.initialize(EnergyConsumptionAnalyzer.java:47)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.initializeRainbowComponents(RainbowMaster.java:209)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.initialize(RainbowMaster.java:131)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.main(RainbowMaster.java:798)
cp1_ta    | [INFO] [1526404757.532940]: Battery charge: 1.1381073152505885Ah
```

**Comment by javier-camara** [comment]
Have you successfully updated the code? It should not be doing that anymore. Can you check that the recompiled version you have has the following method code in simpleconfigurationstore?

	public SimpleConfigurationStore(Properties props) {
		m_source = ConfigHelper.convertToAbsolute(props.getProperty(PropertiesSimpleConfigurationStore.CONFIGURATIONS_SOURCE_PROPKEY));
	//	m_source = "/Users/jcamara/Dropbox/Documents/Work/projects/rainbow-alt/deployments/rainbow-brass/prismtmp/p2cp1/config_list.json";
	}

**Comment by pooyanjamshidi** [comment]
@javier-camara I rebuilt rainbow docker:
```
docker build --no-cache -t cmu-mars/cp1_rb -f Dockerfile-cp1 .
```
So it should have the latest version of the code you pushed. @schmerl can confirm that?

**Comment by pooyanjamshidi** [comment]
I think @schmerl put the binaries somewhere in the able website, so things need to move there I guess.

**Comment by schmerl** [comment]
@pooyanjamshidi  Is this the right issue? Isn't this to do with the battery perturbation issue?

In any case, what makes you say that the planner doesn't come up with a plan that includes charging? I see:

```
(V(1, do SetCP1Config(1) then 2),
V(2, do MoveAbsH(-21.08, 0.00, 0.12, -1.5522) then 3)::
V(3, do MoveAbsH(-20.86, -11.62, 0.12, -0.0123) then 4)::
V(4, do MoveAbsH(1.03, -11.89, 0.12, 0.0000) then 5)::
V(5, do Charge(15.00) then 6)::
V(6, do MoveAbsH(23.19, -11.89, 0.12, 0.0000) then 7)::
V(7, end)::
nil)])
```

There are two things going on here, and I think you quit prematurely:

1. Does the IG get executed? It is outside of Rainbow and so is not affected by exceptions in Rainbow.
2. Rainbow is throwing an exception in the energy consumption part, which is not part of the planner.

**Comment by schmerl** [comment]
@pooyanjamshidi As I said, let's not pollute this issue with every exception that may occur. The exceptions listed above have gone, yes? So this issue can be closed.

**Comment by schmerl** [comment]
Moved discussion to the appropriate issue #85 (or, at least, if not this issue then another issue that helps us reproduce it).

**Comment by pooyanjamshidi** [comment]
@schmerl let's not create an issue per exceptions ;) but yeah this issue can be closed now.
